// Code generated by entc, DO NOT EDIT.

package registerstore

const (
	// Label holds the string label denoting the registerstore type in the database.
	Label = "registerstore"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"

	// EdgeStore holds the string denoting the store edge name in mutations.
	EdgeStore = "store"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeDrug holds the string denoting the drug edge name in mutations.
	EdgeDrug = "drug"

	// Table holds the table name of the registerstore in the database.
	Table = "registerstores"
	// StoreTable is the table the holds the store relation/edge.
	StoreTable = "registerstores"
	// StoreInverseTable is the table name for the Store entity.
	// It exists in this package in order to avoid circular dependency with the "store" package.
	StoreInverseTable = "stores"
	// StoreColumn is the table column denoting the store relation/edge.
	StoreColumn = "store_stores"
	// UserTable is the table the holds the user relation/edge.
	UserTable = "registerstores"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_users"
	// DrugTable is the table the holds the drug relation/edge.
	DrugTable = "registerstores"
	// DrugInverseTable is the table name for the Drug entity.
	// It exists in this package in order to avoid circular dependency with the "drug" package.
	DrugInverseTable = "drugs"
	// DrugColumn is the table column denoting the drug relation/edge.
	DrugColumn = "drug_drugs"
)

// Columns holds all SQL columns for registerstore fields.
var Columns = []string{
	FieldID,
	FieldAmount,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Registerstore type.
var ForeignKeys = []string{
	"drug_drugs",
	"store_stores",
	"user_users",
}

var (
	// AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	AmountValidator func(int) error
)
