// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/Yui/app/ent/drug"
	"github.com/Yui/app/ent/registerstore"
	"github.com/Yui/app/ent/store"
	"github.com/Yui/app/ent/user"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// RegisterstoreCreate is the builder for creating a Registerstore entity.
type RegisterstoreCreate struct {
	config
	mutation *RegisterstoreMutation
	hooks    []Hook
}

// SetAmount sets the amount field.
func (rc *RegisterstoreCreate) SetAmount(i int) *RegisterstoreCreate {
	rc.mutation.SetAmount(i)
	return rc
}

// SetStoreID sets the store edge to Store by id.
func (rc *RegisterstoreCreate) SetStoreID(id int) *RegisterstoreCreate {
	rc.mutation.SetStoreID(id)
	return rc
}

// SetNillableStoreID sets the store edge to Store by id if the given value is not nil.
func (rc *RegisterstoreCreate) SetNillableStoreID(id *int) *RegisterstoreCreate {
	if id != nil {
		rc = rc.SetStoreID(*id)
	}
	return rc
}

// SetStore sets the store edge to Store.
func (rc *RegisterstoreCreate) SetStore(s *Store) *RegisterstoreCreate {
	return rc.SetStoreID(s.ID)
}

// SetUserID sets the user edge to User by id.
func (rc *RegisterstoreCreate) SetUserID(id int) *RegisterstoreCreate {
	rc.mutation.SetUserID(id)
	return rc
}

// SetNillableUserID sets the user edge to User by id if the given value is not nil.
func (rc *RegisterstoreCreate) SetNillableUserID(id *int) *RegisterstoreCreate {
	if id != nil {
		rc = rc.SetUserID(*id)
	}
	return rc
}

// SetUser sets the user edge to User.
func (rc *RegisterstoreCreate) SetUser(u *User) *RegisterstoreCreate {
	return rc.SetUserID(u.ID)
}

// SetDrugID sets the drug edge to Drug by id.
func (rc *RegisterstoreCreate) SetDrugID(id int) *RegisterstoreCreate {
	rc.mutation.SetDrugID(id)
	return rc
}

// SetNillableDrugID sets the drug edge to Drug by id if the given value is not nil.
func (rc *RegisterstoreCreate) SetNillableDrugID(id *int) *RegisterstoreCreate {
	if id != nil {
		rc = rc.SetDrugID(*id)
	}
	return rc
}

// SetDrug sets the drug edge to Drug.
func (rc *RegisterstoreCreate) SetDrug(d *Drug) *RegisterstoreCreate {
	return rc.SetDrugID(d.ID)
}

// Mutation returns the RegisterstoreMutation object of the builder.
func (rc *RegisterstoreCreate) Mutation() *RegisterstoreMutation {
	return rc.mutation
}

// Save creates the Registerstore in the database.
func (rc *RegisterstoreCreate) Save(ctx context.Context) (*Registerstore, error) {
	if _, ok := rc.mutation.Amount(); !ok {
		return nil, &ValidationError{Name: "amount", err: errors.New("ent: missing required field \"amount\"")}
	}
	if v, ok := rc.mutation.Amount(); ok {
		if err := registerstore.AmountValidator(v); err != nil {
			return nil, &ValidationError{Name: "amount", err: fmt.Errorf("ent: validator failed for field \"amount\": %w", err)}
		}
	}
	var (
		err  error
		node *Registerstore
	)
	if len(rc.hooks) == 0 {
		node, err = rc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RegisterstoreMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			rc.mutation = mutation
			node, err = rc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(rc.hooks) - 1; i >= 0; i-- {
			mut = rc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (rc *RegisterstoreCreate) SaveX(ctx context.Context) *Registerstore {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (rc *RegisterstoreCreate) sqlSave(ctx context.Context) (*Registerstore, error) {
	r, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	r.ID = int(id)
	return r, nil
}

func (rc *RegisterstoreCreate) createSpec() (*Registerstore, *sqlgraph.CreateSpec) {
	var (
		r     = &Registerstore{config: rc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: registerstore.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: registerstore.FieldID,
			},
		}
	)
	if value, ok := rc.mutation.Amount(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: registerstore.FieldAmount,
		})
		r.Amount = value
	}
	if nodes := rc.mutation.StoreIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   registerstore.StoreTable,
			Columns: []string{registerstore.StoreColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: store.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   registerstore.UserTable,
			Columns: []string{registerstore.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rc.mutation.DrugIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   registerstore.DrugTable,
			Columns: []string{registerstore.DrugColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: drug.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return r, _spec
}
