// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/Yui/app/ent/drug"
	"github.com/Yui/app/ent/registerstore"
	"github.com/Yui/app/ent/schema"
	"github.com/Yui/app/ent/store"
	"github.com/Yui/app/ent/user"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	drugFields := schema.Drug{}.Fields()
	_ = drugFields
	// drugDescName is the schema descriptor for name field.
	drugDescName := drugFields[0].Descriptor()
	// drug.NameValidator is a validator for the "name" field. It is called by the builders before save.
	drug.NameValidator = drugDescName.Validators[0].(func(string) error)
	registerstoreFields := schema.Registerstore{}.Fields()
	_ = registerstoreFields
	// registerstoreDescAmount is the schema descriptor for amount field.
	registerstoreDescAmount := registerstoreFields[0].Descriptor()
	// registerstore.AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	registerstore.AmountValidator = registerstoreDescAmount.Validators[0].(func(int) error)
	storeFields := schema.Store{}.Fields()
	_ = storeFields
	// storeDescName is the schema descriptor for name field.
	storeDescName := storeFields[0].Descriptor()
	// store.NameValidator is a validator for the "name" field. It is called by the builders before save.
	store.NameValidator = storeDescName.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[2].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
}
