// Code generated by entc, DO NOT EDIT.

package store

const (
	// Label holds the string label denoting the store type in the database.
	Label = "store"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"

	// EdgeStores holds the string denoting the stores edge name in mutations.
	EdgeStores = "stores"

	// Table holds the table name of the store in the database.
	Table = "stores"
	// StoresTable is the table the holds the stores relation/edge.
	StoresTable = "registerstores"
	// StoresInverseTable is the table name for the Registerstore entity.
	// It exists in this package in order to avoid circular dependency with the "registerstore" package.
	StoresInverseTable = "registerstores"
	// StoresColumn is the table column denoting the stores relation/edge.
	StoresColumn = "store_stores"
)

// Columns holds all SQL columns for store fields.
var Columns = []string{
	FieldID,
	FieldName,
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)
