/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntRegisterstoreEdges,
    EntRegisterstoreEdgesFromJSON,
    EntRegisterstoreEdgesFromJSONTyped,
    EntRegisterstoreEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntRegisterstore
 */
export interface EntRegisterstore {
    /**
     * Amount holds the value of the "amount" field.
     * @type {number}
     * @memberof EntRegisterstore
     */
    amount?: number;
    /**
     * 
     * @type {EntRegisterstoreEdges}
     * @memberof EntRegisterstore
     */
    edges?: EntRegisterstoreEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntRegisterstore
     */
    id?: number;
}

export function EntRegisterstoreFromJSON(json: any): EntRegisterstore {
    return EntRegisterstoreFromJSONTyped(json, false);
}

export function EntRegisterstoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntRegisterstore {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'edges': !exists(json, 'edges') ? undefined : EntRegisterstoreEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntRegisterstoreToJSON(value?: EntRegisterstore | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'edges': EntRegisterstoreEdgesToJSON(value.edges),
        'id': value.id,
    };
}


