/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDrug,
    EntDrugFromJSON,
    EntDrugFromJSONTyped,
    EntDrugToJSON,
    EntStore,
    EntStoreFromJSON,
    EntStoreFromJSONTyped,
    EntStoreToJSON,
    EntUser,
    EntUserFromJSON,
    EntUserFromJSONTyped,
    EntUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntRegisterstoreEdges
 */
export interface EntRegisterstoreEdges {
    /**
     * 
     * @type {EntDrug}
     * @memberof EntRegisterstoreEdges
     */
    drug?: EntDrug;
    /**
     * 
     * @type {EntStore}
     * @memberof EntRegisterstoreEdges
     */
    store?: EntStore;
    /**
     * 
     * @type {EntUser}
     * @memberof EntRegisterstoreEdges
     */
    user?: EntUser;
}

export function EntRegisterstoreEdgesFromJSON(json: any): EntRegisterstoreEdges {
    return EntRegisterstoreEdgesFromJSONTyped(json, false);
}

export function EntRegisterstoreEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntRegisterstoreEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'drug': !exists(json, 'Drug') ? undefined : EntDrugFromJSON(json['Drug']),
        'store': !exists(json, 'Store') ? undefined : EntStoreFromJSON(json['Store']),
        'user': !exists(json, 'User') ? undefined : EntUserFromJSON(json['User']),
    };
}

export function EntRegisterstoreEdgesToJSON(value?: EntRegisterstoreEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'drug': EntDrugToJSON(value.drug),
        'store': EntStoreToJSON(value.store),
        'user': EntUserToJSON(value.user),
    };
}


