/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntRegisterstore,
    EntRegisterstoreFromJSON,
    EntRegisterstoreFromJSONTyped,
    EntRegisterstoreToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntStoreEdges
 */
export interface EntStoreEdges {
    /**
     * Stores holds the value of the stores edge.
     * @type {Array<EntRegisterstore>}
     * @memberof EntStoreEdges
     */
    stores?: Array<EntRegisterstore>;
}

export function EntStoreEdgesFromJSON(json: any): EntStoreEdges {
    return EntStoreEdgesFromJSONTyped(json, false);
}

export function EntStoreEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntStoreEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stores': !exists(json, 'stores') ? undefined : ((json['stores'] as Array<any>).map(EntRegisterstoreFromJSON)),
    };
}

export function EntStoreEdgesToJSON(value?: EntStoreEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stores': value.stores === undefined ? undefined : ((value.stores as Array<any>).map(EntRegisterstoreToJSON)),
    };
}


