/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntStoreEdges,
    EntStoreEdgesFromJSON,
    EntStoreEdgesFromJSONTyped,
    EntStoreEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntStore
 */
export interface EntStore {
    /**
     * 
     * @type {EntStoreEdges}
     * @memberof EntStore
     */
    edges?: EntStoreEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntStore
     */
    id?: number;
    /**
     * Name holds the value of the "name" field.
     * @type {string}
     * @memberof EntStore
     */
    name?: string;
}

export function EntStoreFromJSON(json: any): EntStore {
    return EntStoreFromJSONTyped(json, false);
}

export function EntStoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntStore {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntStoreEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function EntStoreToJSON(value?: EntStore | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntStoreEdgesToJSON(value.edges),
        'id': value.id,
        'name': value.name,
    };
}


